export enum ENUM_STATUS_BENEFICIARIO {
  ATIVO = 'ATIVO',
  INATIVO = 'INATIVO',
}

export enum ENUM_ESTADO_CIVIL_BENEFICIARIO {
  SOLTEIRO = 'SOLTEIRO',
  CASADO = 'CASADO',
  VIUVO = 'VIUVO',
  DIVORCIADO = 'DIVORCIADO',
  UNIAO_ESTAVEL = 'UNIAO_ESTAVEL',
}

export enum ENUM_SEXO_BENEFICIARIO {
  MASCULINO = 'M',
  FEMININO = 'F',
}

export enum ENUM_TIPO_MORADIA_BENEFICIARIO {
  PROPRIO = 'Próprio',
  FINANCIADO = 'Financiado',
  ALUGADO = 'Alugado',
  CEDIDO = 'Cedido',
  HERANCA = 'Herança',
  PROGRAMA_SOCIAL = 'Programa Social',
  OCUPACAO = 'Ocupação',
}
