export enum ENUM_STATUS_BENEFICIARIO {
  ATIVO = 'ATIVO',
  INATIVO = 'INATIVO',
}

export enum ENUM_ESTADO_CIVIL_BENEFICIARIO {
  SOLTEIRO = 'SOLTEIRO',
  CASADO = 'CASADO',
  VIUVO = 'VIUVO',
  DIVORCIADO = 'DIVORCIADO',
  UNIAO_ESTAVEL = 'UNIAO_ESTAVEL',
}

export enum ENUM_SEXO_BENEFICIARIO {
  MASCULINO = 'M',
  FEMININO = 'F',
}
