export enum ENUM_RECEBIMENTO_DOACAO_ORIGEM {
  MISSA_DOMINGO = 'MISSA_DOMINGO',
  MISSA_SABADO = 'MISSA_SABADO',
  MISSA_SEMANA = 'MISSA_SEMANA',
  CAMPANHA = 'CAMPANHA',
  PONTUAL = 'PONTUAL',
  OUTROS = 'OUTROS',
}
